redis:
  host: my-redis
  port: 6379

image:
  repository: redis
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 6379

serviceAccount:
  create: true
  name: ""
ingress:
  enabled: false
hpa:
  enabled: false
autoscaling:
  enabled: false
