{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "my-redis-client.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "my-redis-client.labels" . | nindent 4 }}
{{- end }}
